[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "edgar"
version = "0.1.0"
description = "Equation Discovery with Graphical AI Reasoning: an evolutionary framework for discovering scientific equations using LLM-generated programs."
requires-python = ">=3.13"
dynamic = ["dependencies"]

[project.scripts]
edgar = "edgar.cli:run_cli"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["edgar*"]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
addopts = "-m 'not live and not slow'" #By default do not use live API calls or run slow tests
markers = [
    "live: tests that make real LLM API calls",
    "slow: tests that take a long time"
]

[dependency-groups]
dev = ["pre-commit"]

[tool.uv]
package = true

[tool.ruff]
exclude = ["projects", "scripts", "figures", "tests/io/test_task", "tests/io/test_task_no_image", "tests/system/test_task"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
]
ignore = [
    "E501", #line too long
    "E702", #multiple statements on one lines
    "E741", #variables l
]