task:
  data_path: /path/to/data.npy
evolution:
  n_iterations: 2
  batch_size: 3
  n_islands: 4
llms:
  model_llm:
  - gemini-2.5-flash
  - gemini-2.0-flash
  - gemini-2.0-flash
  swear_words: []
scoring:
  gradient_descent:
