"""
Provides core operations for managing "islands" in the evolutionary algorithm,
including program seeding, spawning, sampling, pruning, migration, and deduplication,
as well as the persistence of island membership history.

An island is represented as a set of global `Program` indices. The `island_census`
tracks the membership of each island across generations, enabling historical analysis.

The module implements single-island operations such as pruning, which reduces
an island to its best programs, and sampling, which selects programs based on
uniform or Boltzmann distributions. Cross-island operations, like migration
and deduplication, facilitate genetic exchange and maintain diversity and efficiency
across the entire population.

Example usage:

    # Assume `population` is an initialized Population object and `islands` is a list of sets.
    programs_0 = [population[i] for i in islands[0]]
    programs_1 = [population[i] for i in islands[1]]

    # Prune island_0 to retain the 10 best programs.
    prune(islands, population, evolution_config_dict)

    # Sample 2 parents from island_0 using a Boltzmann distribution.
    parents = boltzmann_sample(programs_0, k=2, temperature=1.0, rng=np.random.default_rng())

    # Migrate 2 programs from island_0 to island_1 via uniform sampling.
    islands[1].update(uniform_sample(programs_0, k=2, rng=np.random.default_rng()))

    # Perform within-island and cross-island deduplication.
    deduplicate(islands, population, evolution_config_dict)

    # Save the current island census after each generation.
    save_island_census(census, "census.json")
"""

from __future__ import annotations
import json
import numpy as np
from itertools import combinations
from .program import Program, BirthCertificate
from .population import Population


# ─────────────────────────────────────────────────────────────────────────
# Initialization: seed and spawn
# ─────────────────────────────────────────────────────────────────────────


def seed(
    population: Population, seed_programs: list[Program], n_islands: int
) -> list[set[int]]:
    """Adds seed programs to the population and initializes all islands.

    This function adds the initial set of `Program` objects to the global `Population`
    and then creates `n_islands` identical islands, each containing the indices
    of all seed programs.

    Args:
        population: The global `Population` object to which seed programs will be added.
            This object is mutated.
        seed_programs: A list of initial `Program` objects to seed the population.
        n_islands: The total number of islands to create.

    Returns:
        A list of `n_islands` sets, where each set contains the global indices
        of all `seed_programs`.

    Raises:
        AssertionError: If the initial `population` is not empty.
    """
    assert len(population) == 0, "Initial population must be empty"
    for program in seed_programs:
        population.add(program)

    seed_indices = {p.idx for p in seed_programs}
    return [set(seed_indices) for _ in range(n_islands)]


def spawn(
    population: Population,
    islands: list[set[int]],
    generation: int,
    mode: str,
    temperature: float,
    batch_size: int,
    num_parents: int,
    rng: np.random.Generator,
) -> None:
    """Samples parents from each island and creates empty `Program` shells.

    For each island, this function samples `num_parents` programs (uniformly at random)
    and uses their indices to create `batch_size` new `Program` shells. Each shell
    receives a `BirthCertificate` detailing its origin (generation, island, batch index,
    parentage, mode, and temperature). These new shells are added to the global
    `population` and their respective birth islands. The shells do not contain
    any code yet; their code will be generated by LLMs in a subsequent step.

    Args:
        population: The global `Population` object where new program shells will be added.
            This object is mutated.
        islands: A list of island sets, where each set contains program indices.
            These sets are mutated to include the indices of newly spawned programs.
        generation: The current generation number of the evolutionary run.
        mode: The current operational mode (e.g., "explore" or "exploit").
        temperature: The temperature parameter used for LLM generation in this generation.
        batch_size: The number of new programs to spawn for each island in the current batch.
        num_parents: The number of parent programs to sample for each new child program.
        rng: The NumPy random number generator to use for sampling parents.
    """
    for island_idx, island in enumerate(islands):
        programs = [population[i] for i in island]

        for batch_idx in range(batch_size):
            parent_indices = list(uniform_sample(programs, k=num_parents, rng=rng))
            child = Program(
                birth=BirthCertificate(
                    generation=generation,
                    island=island_idx,
                    batch_index=batch_idx,
                    mode=mode,
                    temperature=temperature,
                    parent_indices=parent_indices,
                ),
            )
            population.add(child)
            island.add(child.idx)


# ─────────────────────────────────────────────────────────────────────────
# Sampling and pruning
# ─────────────────────────────────────────────────────────────────────────


def prune(islands: list[set[int]], population: Population, evolution: dict) -> None:
    """Prunes each island to a fixed number of the best-performing programs.

    This function iterates through each island and sorts its programs based on their
    `discover.final` loss. It retains only the `critical_population_size - n_migrants`
    best programs. Programs with `None` or `inf` losses are explicitly handled by
    being assigned `float("inf")` for sorting purposes, ensuring they are ranked
    as the worst performers.

    Args:
        islands: A list of island sets (each set contains program indices).
            The sets in this list are mutated in-place.
        population: The global `Population` object used to resolve program indices
            to `Program` objects for loss evaluation.
        evolution: A dictionary containing evolutionary configuration parameters,
            specifically `critical_population_size` and `n_migrants`.
    """
    keep_n = evolution["critical_population_size"] - evolution["n_migrants"]
    for i, island in enumerate(islands):
        programs = [population[idx] for idx in island]
        # explicitly handle cases where the loss is None or inf to avoid sorting issues
        ranked = sorted(
            programs,
            key=lambda p: (
                float("inf")
                if p.program_losses.discover.final is None
                else p.program_losses.discover.final
            ),
        )
        islands[i] = {p.idx for p in ranked[:keep_n]}


def uniform_sample(
    programs: list[Program], k: int, rng: np.random.Generator
) -> set[int]:
    """Samples `k` global program indices uniformly at random from a list of programs.

    Args:
        programs: A list of `Program` objects from which to sample.
        k: The number of program indices to sample.
        rng: The NumPy random number generator to use for sampling.

    Returns:
        A set of `k` global program indices.

    Raises:
        ValueError: If `k` is greater than the number of available programs.
    """
    if k > len(programs):
        raise ValueError(
            f"k={k} exceeds number of programs sampled from {len(programs)}"
        )
    chosen = rng.choice(len(programs), size=k, replace=False)
    return {programs[j].idx for j in chosen}


def boltzmann_sample(
    programs: list[Program], k: int, temperature: float, rng: np.random.Generator
) -> set[int]:
    r"""Samples `k` global program indices using a Boltzmann distribution.

    The probability of selecting a program is based on its `discover.final` loss,
    with fitter programs (lower loss) having a higher probability of selection.
    The `temperature` parameter controls the selection pressure: a high temperature
    results in a more uniform sampling, while a low temperature causes the best
    programs to dominate the selection. `NaN` and `inf` losses are converted to
    a finite large value (`worst_finite + 1.0`) to ensure robust probability calculation.

    The probability $P_i$ for selecting program $i$ is calculated as:
    $$ P_i = \frac{e^{g_i}}{\sum_j e^{g_j}} $$
    where:
    $$ g_i = \frac{-z_i}{\max(\text{temperature}, 10^{-3})} $$
    $$ z_i = \frac{\text{loss}_i - \text{loss}_{\min}}{\text{std}_{\text{loss}} + 10^{-6}} $$

    Args:
        programs: A list of `Program` objects from which to sample.
        k: The number of program indices to sample.
        temperature: The temperature parameter for the Boltzmann distribution.
            Higher values lead to more exploration, lower values to more exploitation.
        rng: The NumPy random number generator to use for sampling.

    Returns:
        A set of `k` global program indices.

    Raises:
        ValueError: If `k` is greater than the number of available programs.
    """
    if k > len(programs):
        raise ValueError(
            f"k={k} exceeds number of programs sampled from {len(programs)}"
        )
    losses = np.array(
        [p.program_losses.discover.final for p in programs], dtype=float
    )  # dtype = float converts None to nan
    losses = np.where(
        np.isnan(losses) | np.isinf(losses), float("inf"), losses
    )  # convert NaN, +-inf to +inf
    finite_losses = losses[np.isfinite(losses)]
    worst_finite = finite_losses.max() if len(finite_losses) > 0 else 0.0
    losses = np.where(
        np.isinf(losses), worst_finite + 1.0, losses
    )  # convert +inf to worst_finite + 1
    logits = (
        -(losses - losses.min()) / (np.std(losses) + 1e-6) / max(temperature, 1e-3)
    )  # compute g_i logits
    logits -= (
        logits.max()
    )  # ensures largest value being exponentiated is 0, so exp(g_i) is in [0, 1]
    probs = np.exp(logits)
    probs /= probs.sum()
    chosen = rng.choice(len(programs), size=k, replace=False, p=probs)
    return {programs[j].idx for j in chosen}


# ─────────────────────────────────────────────────────────────────────────
# Migration
# ─────────────────────────────────────────────────────────────────────────


def migrate(
    islands: list[set[int]],
    population: Population,
    evolution: dict,
    temperature: float,
    rng: np.random.Generator,
) -> None:
    """Samples migrants from each island and transfers them to destination islands.

    For each island, `n_migrants` programs are sampled using a Boltzmann distribution
    (biased towards better-performing programs). These sampled programs are then
    added to their respective destination islands, as defined by the `topology`
    configuration. The `temperature` parameter from the schedule is warped
    ($T_{\text{warped}} = (T - 1.0)^4$) to create a sharp decay, making migration
    strongly selective later in the run.

    Args:
        islands: A list of island sets (each set contains program indices).
            This list and its contained sets are mutated in-place.
        population: The global `Population` object used to resolve program indices
            to `Program` objects for Boltzmann sampling.
        evolution: A dictionary containing evolutionary configuration parameters,
            specifically `n_migrants` and `topology`.
        temperature: The base temperature from the generation schedule. This value
            is warped before being used in Boltzmann sampling for migration.
        rng: The NumPy random number generator to use for sampling migrants.

    Raises:
        ValueError: If the length of the `topology` does not match the number of islands.
    """
    # Temperature needs warping before being passed to boltzmann_sample.
    # Raw temperature from schedule() lives in [1, 2]. The correct transform is
    #     T_warped = (T - 1.0) ** 4
    # which maps [1, 2] -> [0, 1] with a sharp decay, so migration becomes
    # strongly selective late in the run. Confirmed in the old hypothesis_engine.py.

    if len(islands) != len(evolution["topology"]):
        raise ValueError("Length of topology must match number of islands")

    n_migrants = evolution["n_migrants"]
    topology = evolution["topology"]
    T_warped = (temperature - 1.0) ** 4

    # First collect which programs will be migrated
    updates = []
    for island in islands:
        programs = [population[idx] for idx in island]
        sampled = boltzmann_sample(
            programs, k=n_migrants, temperature=T_warped, rng=rng
        )
        updates.append(sampled)

    # Copy the migrants across to destination islands, updating all islands simultaneously
    for destination, migrants in zip(topology, updates):
        islands[destination].update(migrants)


# ─────────────────────────────────────────────────────────────────────────
# Deduplication
# ─────────────────────────────────────────────────────────────────────────


def _loss(p: Program) -> float:
    """Retrieves the final discover loss of a program, handling None values.

    Args:
        p: The `Program` object.

    Returns:
        The final discover loss as a float. Returns `float("inf")` if the loss is `None`.
    """
    v = p.program_losses.discover.final
    return v if v is not None else float("inf")


def _are_duplicates(
    p_i: Program, p_j: Program, loss_tol: float, cosine_tol: float
) -> bool:
    """Checks if two programs are considered duplicates based on multiple criteria.

    Two programs are identified as duplicates if they satisfy all of the following conditions:
    1. They have the same number of parameters (`n_params`).
    2. Their `discover.final` losses are within a specified `loss_tol`.
    3. The cosine similarity of their `eval_fingerprint` arrays is greater than or equal
       to a specified `cosine_tol`.

    Args:
        p_i: The first `Program` object to compare.
        p_j: The second `Program` object to compare.
        loss_tol: The absolute tolerance for the difference in `discover.final` losses.
        cosine_tol: The minimum cosine similarity required between `eval_fingerprint` arrays.

    Returns:
        True if the two programs are considered duplicates, False otherwise.
    """
    if p_i.n_params is None or p_j.n_params is None or p_i.n_params != p_j.n_params:
        return False
    if p_i.eval_fingerprint is None or p_j.eval_fingerprint is None:
        return False
    if (
        p_i.program_losses.discover.final is not None
        and p_j.program_losses.discover.final is not None
    ):
        if (
            abs(p_i.program_losses.discover.final - p_j.program_losses.discover.final)
            > loss_tol
        ):
            return False
    y_i = p_i.eval_fingerprint.flatten()
    y_j = p_j.eval_fingerprint.flatten()
    cosine = np.dot(y_i, y_j) / (np.linalg.norm(y_i) * np.linalg.norm(y_j) + 1e-6)
    return bool(cosine >= cosine_tol)


def deduplicate_inner(
    islands: list[set[int]],
    population: Population,
    loss_tol: float = 0.01,
    cosine_tol: float = 0.95,
) -> None:
    """Removes near-duplicate programs within each island.

    This function iterates through each island and identifies pairs of programs
    that are considered duplicates based on `_are_duplicates`. For each identified
    duplicate pair, the program with the higher `discover.final` loss is removed
    from the island.

    Args:
        islands: A list of island sets (each set contains program indices).
            The sets in this list are mutated in-place.
        population: The global `Population` object used to resolve program indices
            to `Program` objects for comparison.
        loss_tol: The absolute tolerance for the difference in `discover.final` losses
            to consider programs as duplicates. Defaults to 0.01.
        cosine_tol: The minimum cosine similarity between `eval_fingerprint` arrays
            to consider programs as duplicates. Defaults to 0.95.
    """
    for i, island in enumerate(islands):
        programs = [population[idx] for idx in island]
        to_remove = set()

        for p_j, p_k in combinations(programs, 2):
            if p_j.idx in to_remove or p_k.idx in to_remove:
                continue
            if not _are_duplicates(p_j, p_k, loss_tol, cosine_tol):
                continue
            loser = (
                p_j
                if p_j.program_losses.discover.final
                >= p_k.program_losses.discover.final
                else p_k
            )
            to_remove.add(loser.idx)

        islands[i] = {p.idx for p in programs if p.idx not in to_remove}


def deduplicate_outer(
    islands: list[set[int]],
    population: Population,
    min_island_size: int = 6,
    loss_tol: float = 0.01,
    cosine_tol: float = 0.99,
) -> None:
    """Removes duplicate programs across different islands, prioritizing lower-loss copies.

    This function compares programs between all pairs of islands. It only performs
    cross-island deduplication if both islands in a pair have at least `min_island_size`
    programs. When a duplicate pair is found, the program with the higher
    `discover.final` loss is removed. In case of a tie in loss, the program from the
    higher-indexed island is removed. This function assumes that `deduplicate_inner`
    has already been applied, ensuring at most one duplicate of a program on any
    given island.

    Args:
        islands: A list of island sets (each set contains program indices).
            The sets in this list are mutated in-place.
        population: The global `Population` object used to resolve program indices
            to `Program` objects for comparison.
        min_island_size: The minimum number of programs an island must have for
            cross-island deduplication to be attempted. Defaults to 6.
        loss_tol: The absolute tolerance for the difference in `discover.final` losses
            to consider programs as duplicates. Defaults to 0.01.
        cosine_tol: The minimum cosine similarity between `eval_fingerprint` arrays
            to consider programs as duplicates. Defaults to 0.99.
    """
    # Filter out islands that are too small for outer deduplication.
    # Note: This is a copy of the list of sets, but not copies of the sets themselves.
    # So `islands[loser_island].remove(loser_idx)` still modifies the original islands list.
    filtered_islands = [
        (idx, island)
        for idx, island in enumerate(islands)
        if len(island) >= min_island_size
    ]

    for i_idx, j_idx in combinations(range(len(filtered_islands)), 2):
        original_idx_i, island_i = filtered_islands[i_idx]
        original_idx_j, island_j = filtered_islands[j_idx]

        snapshot_i = list(island_i)
        snapshot_j = list(island_j)

        for idx_j in snapshot_j:
            if (
                idx_j not in islands[original_idx_j]
            ):  # Check if it hasn't been removed by a previous deduplication
                continue
            p_j = population[idx_j]

            for idx_i in snapshot_i:
                if (
                    idx_i not in islands[original_idx_i]
                ):  # Check if it hasn't been removed by a previous deduplication
                    continue
                p_i = population[idx_i]

                if not _are_duplicates(p_i, p_j, loss_tol, cosine_tol):
                    continue

                if _loss(p_i) < _loss(p_j):
                    loser_original_island_idx, loser_idx = original_idx_j, idx_j
                elif _loss(p_i) > _loss(p_j):
                    loser_original_island_idx, loser_idx = original_idx_i, idx_i
                else:
                    # Tie in loss: keep program from the lower-indexed island
                    loser_original_island_idx, loser_idx = original_idx_j, idx_j

                islands[loser_original_island_idx].remove(loser_idx)
                break  # _deduplicate_inner ensures at most one duplicate of a program on the other island


def deduplicate(
    islands: list[set[int]],
    population: Population,
    evolution: dict,
    loss_tol: float = 0.01,
    cosine_tol: float = 0.95,
) -> None:
    """Applies both within-island and between-island deduplication to the population.

    This function first calls `deduplicate_inner` to remove redundant programs
    within each island. Subsequently, it calls `deduplicate_outer` to eliminate
    duplicates found across different islands. The `min_island_size` for
    cross-island deduplication is dynamically calculated as 75% of the
    `critical_population_size` specified in the evolution configuration.

    Args:
        islands: A list of island sets (each set contains program indices).
            The sets in this list are mutated in-place.
        population: The global `Population` object used to resolve program indices
            to `Program` objects.
        evolution: A dictionary containing evolutionary configuration parameters,
            specifically `critical_population_size`.
        loss_tol: The absolute tolerance for the difference in `discover.final` losses
            to consider programs as duplicates. Defaults to 0.01.
        cosine_tol: The minimum cosine similarity between `eval_fingerprint` arrays
            to consider programs as duplicates. Defaults to 0.95.
    """
    n_critical = evolution.get("critical_population_size", 12)
    min_island_size = int(
        0.75 * n_critical
    )  # only remove cross-island duplicates if both islands have at least 75% of critical population size

    deduplicate_inner(islands, population, loss_tol, cosine_tol)
    deduplicate_outer(islands, population, min_island_size, loss_tol, cosine_tol)


# ─────────────────────────────────────────────────────────────────────────
# Census: save and load island membership history
# ─────────────────────────────────────────────────────────────────────────


def save_island_census(census: list[list[set[int]]], path: str) -> None:
    """Saves the island census to a JSON file.

    The island census tracks the membership of each island at the end of every generation,
    where `census[island_id][generation]` is a set of program indices. The data is
    serialized to JSON and written to the specified path atomically (write-tmp-then-rename)
    to ensure that external readers (e.g., the dashboard) never encounter a partially-written
    or corrupted file.

    Args:
        census: A list of lists of sets, representing the island census history.
        path: The file path where the census will be saved.
    """
    from ..io.status import atomic_write_text

    payload = json.dumps([[list(s) for s in island] for island in census])
    atomic_write_text(path, payload)


def load_island_census(path: str) -> list[list[set[int]]]:
    """Loads the island census from a JSON file.

    This function reads a JSON file containing the serialized island census and
    deserializes it back into the original data structure (list of lists of sets of integers).

    Args:
        path: The file path from which to load the census.

    Returns:
        A list of lists of sets, representing the loaded island census history.
    """
    with open(path) as f:
        data = json.load(f)
    return [[set(s) for s in island] for island in data]


def f(x):
    """
    This a dummy function to test the docbot and see what it does
    """
    return x
