task:
  data_path: /home/reilly/datasets/spontaneous_data/spont_M161025_MP030_20161120.mat
evolution:
  n_iterations: 3
  batch_size: 3
  n_islands: 4
llms:
  model_llm:
  - gemini-2.5-pro
  - gemini-2.0-flash
  swear_words:
  - sklearn
  - PLSRegression
  - scipy.optimize
  - optimize.minimize
  - curve_fit
  - cvxpy
  - torch
  - tensorflow
scoring:
  param_penalty_weight: 0.0
  parameter_estimation:
    param_estimator_refinement_rounds: 0
    timeout_s: 5.0
  gradient_descent:
    max_iter: 200
    learning_rate: 0.01
    timeout_s: 30.0
