task: orientation_tuning
load_and_process_data_fn: experiments.orientation_tuning.data_parser.load_and_process_data
normalize_response: experiments.orientation_tuning.data_parser.normalize_response
data_path: /home/dabin/data/stringer_2020/gratings_drifting_GT1_2019_04_12_1.npy