io:
  data_path: /Users/reillytilbury/Desktop/Toroidal_topology_grid_cell_data/rat_q_grid_modules_1_2.npz
evolution:
  n_iterations: 5
scoring:
  gradient_descent:
    max_iter: 100
    learning_rate: 0.001
