task:
  data_path: /home/reilly/datasets/image_responses/FX8_nat60k_2023_05_16.npz
evolution:
  n_iterations: 3
  time_limit: 45
  n_islands: 4
  batch_size: 4
scoring:
  parameter_estimation:
    param_estimator_refinement_rounds: 0
  gradient_descent:
    max_iter: 100
    learning_rate: 0.03
